### ISSUE TITLE
windows 8.1 key listing not working

### ISSUE THREAD

**Issue by lancebermudez** [isislovecruft/python-gnupg#119]
import gnupg
gpg = gnupg.GPG(binary='gpg.exe',
                homedir='C:/Users/lance/AppData/Roaming/gnupg',
                keyring='pubring.gpg',
                secring='secring.gpg',
                verbose=True)
public_keys = gpg.list_keys()
print(public_keys)

using python3.4 and python-gnugpg version 2.0.2

error i get is
Traceback (most recent call last):
  File "C:/Users/lance/Pictures/test0.py", line 14, in <module>
    verbose=True)
  File "C:\Python34\lib\site-packages\gnupg\gnupg.py", line 162, in **init**
    self.create_trustdb()
  File "C:\Python34\lib\site-packages\gnupg\gnupg.py", line 172, in create_trustdb
    if self.is_gpg2():
  File "C:\Python34\lib\site-packages\gnupg\gnupg.py", line 212, in is_gpg2
    return _util._is_gpg2(self.binary_version)
  File "C:\Python34\lib\site-packages\gnupg_util.py", line 529, in _is_gpg2
    (major, minor, micro) = _match_version_string(version)
  File "C:\Python34\lib\site-packages\gnupg_util.py", line 607, in _match_version_string
    major, minor, micro = int(g[0]), int(g[2]), int(g[4])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by ksfrazier** [comment]
likewise on windows 10

**Comment by ksfrazier** [comment]
changed binary to be 
binary='C:/Progra~1/GNU/GnuPG/pub/gpg.exe'

that gets me further... but more problems after that ;-)

**Comment by SkiFire13** [comment]
Same problem... unable to solve

**Comment by axfelix** [comment]
I can duplicate. This is the output of gpg2 installed from choco:

    $ gpg2 --version
    gpg (GnuPG) 2.0.30 (Gpg4win 2.3.3)
    libgcrypt 1.6.6
    Copyright (C) 2015 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.
    
    Home: C:/Users/axfel/AppData/Roaming/gnupg
    Supported algorithms:
    Pubkey: RSA, RSA, RSA, ELG, DSA
    Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
            CAMELLIA128, CAMELLIA192, CAMELLIA256
    Hash: MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
    Compression: Uncompressed, ZIP, ZLIB, BZIP2

**Comment by axfelix** [comment]
this regex seems to work fine on both the Windows and Linux gpg2 --version output:

`'(\d+)(\.)(\d+)(\.)(\d+)'`

albeit I can't quite tell why the current one is failing, or how you're doing the version check currently.

**Comment by axfelix** [comment]
Unfortunately, I'm also getting some issues trying to run this in Windows 10's Ubuntu 14.04 subsystem with all of the dependencies (as far as I can tell) installed:

    >>> gpg = gnupg.GPG()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/gnupg/gnupg.py", line 125, in __init__
        ignore_homedir_permissions=ignore_homedir_permissions,
      File "/usr/local/lib/python2.7/dist-packages/gnupg/_meta.py", line 232, in __init__
        self._check_sane_and_get_gpg_version()
      File "/usr/local/lib/python2.7/dist-packages/gnupg/_meta.py", line 502, in _check_sane_and_get_gpg_version
        proc.terminate()
      File "/usr/lib/python2.7/subprocess.py", line 1551, in terminate
        self.send_signal(signal.SIGTERM)
      File "/usr/lib/python2.7/subprocess.py", line 1546, in send_signal
        os.kill(self.pid, sig)
    OSError: [Errno 3] No such process

**Comment by isislovecruft** [comment]
Hi @ksfrazier, thanks for reporting this! As you noted above, you have to specify the *full path* to the gpg binary.

@axfelix Thanks for uncovering some more issues! I've added a patch (36800a6bd) to fix the regex and allow multiple digits for the revision semantic version number (but not major or minor, because any binary reporting to have version `23.1.0` or `1.23.0` would be lying). I've also added another patch (597dd2dd5) to better handle exceptions when the user doesn't specify a full path to the binary.

**Comment by isislovecruft** [comment]
This should be fixed in python-gnupg version 2.2.0.

**Comment by isislovecruft** [comment]
@axfelix @ksfrazier Please feel free to reopen if python-gnupg 2.2.0 doesn't work for you!

**Comment by axfelix** [comment]
I'm afraid I'm still having the issue...

    >>> gpg = gnupg.GPG(binary="C:/Program Files (x86)/GNU/GnuPG/pub/gpg2.exe", homedir="C:/Users/axfel/.config/python-gnupg")
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "C:\ProgramData\chocolatey\lib\python3\tools\lib\site-packages\gnupg\gnupg.py", line 162, in __init__
        self.create_trustdb()
      File "C:\ProgramData\chocolatey\lib\python3\tools\lib\site-packages\gnupg\gnupg.py", line 172, in create_trustdb
        if self.is_gpg2():
      File "C:\ProgramData\chocolatey\lib\python3\tools\lib\site-packages\gnupg\gnupg.py", line 212, in is_gpg2
        return _util._is_gpg2(self.binary_version)
      File "C:\ProgramData\chocolatey\lib\python3\tools\lib\site-packages\gnupg\_util.py", line 531, in _is_gpg2
        (major, minor, micro) = _match_version_string(version)
      File "C:\ProgramData\chocolatey\lib\python3\tools\lib\site-packages\gnupg\_util.py", line 627, in _match_version_string
        version)
    gnupg._util.GnuPGVersionError: Could not parse GnuPG version from: ''

    $ pip show gnupg
    Name: gnupg
    Version: 2.2.0
    Summary: A Python wrapper for GnuPG
    Home-page: https://github.com/isislovecruft/python-gnupg
    Author: Isis Agora Lovecruft
    Author-email: isis@patternsinthevoid.net
    License: GPLv3+
Location: c:\programdata\chocolatey\lib\python3\tools\lib\site-packages
Requires: psutil

**Comment by kumrzz** [comment]
hey @axfelix, can you please try using the non-spaced version of Program Files?
i.e. `'C:/Progra~2/GNU/GnuPG/pub/gpg2.exe'` instead of
&nbsp; `'C:/Program Files (x86)/GNU/GnuPG/pub/gpg2.exe'` ... seemed to work for me(:gb:)

to devs(@isislovecruft?) , I see in `gnupg/_meta.py`(currently L603):
`if platform.system() == "Windows":`
&emsp;`# TODO figure out what the hell is going on there.`
&emsp;`  expand_shell = True`

this relates to: https://docs.python.org/2/library/subprocess.html :
> The subprocess module allows you to spawn new processes, connect to their input/output/error pipes, and obtain their return codes. 
> class subprocess.Popen(): Execute a child program in a new process.
> The shell argument (which defaults to False) specifies whether to use the shell as the program to execute. If shell is True, it is recommended to pass args as a string rather than as a sequence.
> On Unix with shell=True, the shell defaults to /bin/sh.
> On Windows with shell=True, the COMSPEC environment variable specifies the default shell. The only time you need to specify shell=True on Windows is when the command you wish to execute is built into the shell (e.g. dir or copy). You do not need shell=True to run a batch file or console-based executable.

Therefore, the repo seems to be dealing with these parameters correctly(True@WinX, False@Linux).
(not going to bother doing anything further in the hope u guys can simply comment the code up when u next push a commit, esp. since you'd do a better/more relevant:owl: summary.

**Comment by axfelix** [comment]
that worked! God, Windows is the worst sometimes. I spent a while googling to make sure I wasn't hitting any Python path expansion issues before my last comment... thanks a ton! Sorry for the trouble.

**Comment by kumrzz** [comment]
mate, u have no idea what an arseache this was for me! I literally had to drill down into each component library and submodule to get to the culprit hehe ... dammit Windows! 😡

**Comment by axfelix** [comment]
Wouldn't have even hit the issue if git bash shipped with gpg2 rather than 1.x, or if gpg2 installed via choco didn't go to a path with spaces in it by default...

**Comment by liudude123** [comment]
this is so seriously broken:
keydir = "keys"
gpgbin = r"C:/Progra~2/GNU/GnuPG/pub/gpg2.exe"
gpg = gnupg.GPG(binary=gpgbin, homedir=keydir, ignore_homedir_permissions=True) 
references 
.\keys\keyspubring.gpg
.\keys\keyssecring.gpg
this makes no sense, when I originally had a C:/path/to/keyfile for keydir, it would double that and then add the gpg file name. This was the only way I could get it to work because I can move the key files to a place where it would look for it
